# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cadc82cdc9cf756babd7f7924454c18c663b6e5a7e686a4d3c5c8e32f7a33d2f67c26e5a921376500197befe5204252e6cc04c2f6ca8b6d164c29da86000fdd2

test:
  secret_key_base: 36b8b2fe0f102cbf8f828dd07f1370b4feff52dd559f78d785b4b4e7d1ad6b60217069ea106ed0ad0905819034f7e7546cc7e6920e5e69e244bba6a21244dadf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
